// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SSLboard.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	SSLboard.proto

It has these top-level messages:
	Message
	Credentials
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Token     string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Group     string `protobuf:"bytes,4,opt,name=group" json:"group,omitempty"`
	Msg       string `protobuf:"bytes,5,opt,name=msg" json:"msg,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Message) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Message) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Credentials struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Credentials)(nil), "pb.Credentials")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SSLboard service

type SSLboardClient interface {
	Authenticate(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Credentials, error)
	Get(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Post(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	End(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Credentials, error)
}

type sSLboardClient struct {
	cc *grpc.ClientConn
}

func NewSSLboardClient(cc *grpc.ClientConn) SSLboardClient {
	return &sSLboardClient{cc}
}

func (c *sSLboardClient) Authenticate(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Credentials, error) {
	out := new(Credentials)
	err := grpc.Invoke(ctx, "/pb.SSLboard/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSLboardClient) Get(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/pb.SSLboard/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSLboardClient) Post(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/pb.SSLboard/Post", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSLboardClient) End(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Credentials, error) {
	out := new(Credentials)
	err := grpc.Invoke(ctx, "/pb.SSLboard/end", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SSLboard service

type SSLboardServer interface {
	Authenticate(context.Context, *Credentials) (*Credentials, error)
	Get(context.Context, *Message) (*Message, error)
	Post(context.Context, *Message) (*Message, error)
	End(context.Context, *Credentials) (*Credentials, error)
}

func RegisterSSLboardServer(s *grpc.Server, srv SSLboardServer) {
	s.RegisterService(&_SSLboard_serviceDesc, srv)
}

func _SSLboard_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSLboardServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SSLboard/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSLboardServer).Authenticate(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSLboard_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSLboardServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SSLboard/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSLboardServer).Get(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSLboard_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSLboardServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SSLboard/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSLboardServer).Post(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSLboard_End_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSLboardServer).End(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SSLboard/End",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSLboardServer).End(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _SSLboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SSLboard",
	HandlerType: (*SSLboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _SSLboard_Authenticate_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SSLboard_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _SSLboard_Post_Handler,
		},
		{
			MethodName: "end",
			Handler:    _SSLboard_End_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SSLboard.proto",
}

func init() { proto.RegisterFile("SSLboard.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xeb, 0xa6, 0x85, 0xf4, 0x8a, 0x00, 0x9d, 0x18, 0xac, 0x88, 0x01, 0x3c, 0xc1, 0x92,
	0xa1, 0x3c, 0x01, 0x42, 0x88, 0x05, 0x24, 0x44, 0x9f, 0xc0, 0x21, 0xa7, 0x50, 0x41, 0x62, 0xcb,
	0x77, 0x11, 0x33, 0x6f, 0xc4, 0x23, 0x22, 0xbb, 0xa5, 0x94, 0x0c, 0x88, 0xcd, 0xbf, 0xef, 0xb3,
	0x7e, 0xe7, 0x3f, 0x70, 0xb8, 0x5c, 0xde, 0x57, 0xce, 0x86, 0xba, 0xf4, 0xc1, 0x89, 0xc3, 0xb1,
	0xaf, 0xcc, 0x87, 0x82, 0xfd, 0x07, 0x62, 0xb6, 0x0d, 0xe1, 0x09, 0x4c, 0xc5, 0xbd, 0x52, 0xa7,
	0xd5, 0x99, 0xba, 0x98, 0x3d, 0xad, 0x01, 0x4f, 0x61, 0x26, 0xab, 0x96, 0x58, 0x6c, 0xeb, 0xf5,
	0x38, 0x35, 0x3f, 0x01, 0x16, 0x90, 0xf7, 0x4c, 0xa1, 0xb3, 0x2d, 0xe9, 0x2c, 0x95, 0x5b, 0x8e,
	0xbe, 0x26, 0xb8, 0xde, 0xeb, 0xc9, 0xda, 0x97, 0x00, 0x8f, 0x21, 0x6b, 0xb9, 0xd1, 0xd3, 0x94,
	0xc5, 0xa5, 0xb9, 0x85, 0xf9, 0x4d, 0xa0, 0x9a, 0x3a, 0x59, 0xd9, 0x37, 0xfe, 0xa5, 0x54, 0x03,
	0x65, 0x01, 0xb9, 0xb7, 0xcc, 0xef, 0x2e, 0xd4, 0x9b, 0xb3, 0x6c, 0x79, 0xf1, 0xa9, 0x20, 0xff,
	0xbe, 0x21, 0x2e, 0xe0, 0xe0, 0xba, 0x97, 0x97, 0xe8, 0x7c, 0xb6, 0x42, 0x78, 0x54, 0xfa, 0xaa,
	0xdc, 0x99, 0x52, 0x0c, 0x03, 0x33, 0xc2, 0x73, 0xc8, 0xee, 0x48, 0x70, 0x1e, 0x9b, 0xcd, 0x9b,
	0x14, 0xbb, 0x60, 0x46, 0x68, 0x60, 0xf2, 0xe8, 0xf8, 0xef, 0x3d, 0x97, 0x90, 0x51, 0x57, 0xff,
	0x67, 0x62, 0xb5, 0x97, 0x3e, 0xe2, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x51, 0x00, 0x85,
	0x9a, 0x01, 0x00, 0x00,
}
